# -*- coding: utf-8 -*-
"""Cafezao

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfB360J0yG1eyIDJs6kDZaqb5v1DKxXc
"""

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np

X = np.array([

#espressos em pesquisa
    [14.0, 28, 25],
    [15.0, 30, 28],
    [18.0, 36, 30],
    [20.0, 40, 32],
    [16.0, 32, 27],
    [17.0, 34, 29],
    [19.0, 38, 31],
    [14.5, 29, 26],
    [18.5, 37, 33],
    [21.0, 42, 35],
#coados em pesquisa
    [15.0, 225, 200],
    [20.0, 300, 240],
    [24.0, 360, 280],
    [18.0, 270, 220],
    [22.0, 330, 260],
    [16.0, 240, 210],
    [19.0, 285, 230],
    [21.0, 315, 250],
    [25.0, 375, 290],
    [17.5, 260, 215],
#capuccinos em pesquisa
    [14.0, 150, 26],
    [18.0, 180, 30],
    [16.0, 160, 28],
    [20.0, 180, 33],
    [15.0, 150, 27],
    [17.0, 170, 29],
    [19.0, 180, 32],
    [14.5, 155, 25],
    [18.5, 175, 31],
    [15.5, 160, 28]
])

y = np.array([
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2
])

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y) #proporção dos tipo de café fique perfeitamente igual

modelo_arvore = DecisionTreeClassifier(random_state=42)
modelo_arvore.fit(X_treino, y_treino)

acc_treino_arvore = accuracy_score(y_treino, modelo_arvore.predict(X_treino))
acc_teste_arvore = accuracy_score(y_teste, modelo_arvore.predict(X_teste))

modelo_knn = KNeighborsClassifier(n_neighbors=3)
modelo_knn.fit(X_treino, y_treino)

acc_treino_knn = accuracy_score(y_treino, modelo_knn.predict(X_treino))
acc_teste_knn = accuracy_score(y_teste, modelo_knn.predict(X_teste))

print("CAFEZÃO")
print("")
print("Árvore de Decisão")
print("Nota do Treino:", acc_treino_arvore)
print("Nota do Teste:", acc_teste_arvore)
print("")
print("KNN (k=3)")
print("Nota do Treino:", acc_treino_knn)
print("Nota do Teste:", acc_teste_knn)

cafes = {0: "Espresso", 1: "Café Coado", 2: "Cappuccino"}
novos_X = []
novos_y = []

print("\nAnálise")

# pra testar mude os numeros aqui blz ikaro

po_da_plateia = 15
ml_da_plateia = 225
segundos_da_plateia = 200

nomes_cafes = {0: "espresso", 1: "café coado", 2: "cappuccino "}
amostra_nova = np.array([[po_da_plateia, ml_da_plateia, segundos_da_plateia]])
predicao = modelo_arvore.predict(amostra_nova)[0]

print(f"Dados digitados: {po_da_plateia}g | {ml_da_plateia}ml | {segundos_da_plateia}s")
print("A IA previu:", nomes_cafes[predicao])

