# -*- coding: utf-8 -*-
"""IA Projeto Integrado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvaO24FFZzxhmxfUE_6SZSiNHW2JL9JC
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import joblib
from google.colab import files

X = np.array([
    [4095], [3800], [3500], [3200], [3950], [3700], [3400], [3100], [4000], [3600],
    [2100], [2048], [2000], [2050], [1980], [2090], [2030], [2060], [1990], [2020],
    [1200], [800], [400], [1500], [100], [950], [1350], [600], [1100], [50]
])

y = np.array([
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2
])

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)
modelo_arvore = DecisionTreeClassifier(random_state=42)
modelo_arvore.fit(X_treino, y_treino)

acc_treino_arvore = accuracy_score(y_treino, modelo_arvore.predict(X_treino))
acc_teste_arvore = accuracy_score(y_teste, modelo_arvore.predict(X_teste))

modelo_knn = KNeighborsClassifier(n_neighbors=3)
modelo_knn.fit(X_treino, y_treino)

acc_treino_knn = accuracy_score(y_treino, modelo_knn.predict(X_treino))
acc_teste_knn = accuracy_score(y_teste, modelo_knn.predict(X_teste))

print("Monitoramento de gasolina")
print ("arvore de decisão")
print ("Nota do treino:", acc_treino_arvore)
print ("Nota do teste:", acc_teste_arvore)
print ("knn")
print ("Nota do treino:", acc_treino_knn)
print ("Nota do teste:", acc_teste_knn)

joblib.dump(modelo_arvore, 'modelo_ia.pkl')
print("\arquivo 'modelo_ia.pkl' gerado")

files.download('modelo_ia.pkl')